Algoritmo "MeuPrimeiroAlgoritmo"
// AUTOR: CARLOS MANDELE
// DATA: 13/09/2023
Var
// SEÇÂO DE DECLARAÇÃO DE VARÁVEIS
nome:caracter
idade:inteiro
altura:real
casado:logico
inicio
// SEÇÂO DE COMANDOS
escreval("Digite seu  nome")
leia(nome)
escreval("Digite sua idade")
leia(idade)
escreval("Digite sua altura")
leia(altura)
escreval("Seu nome é", nome, ",sua idade é", idade, ", e sua altura é", altura)

fimalgoritmo